// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ColorsBackupRestore() {
  return window['go']['main']['App']['ColorsBackupRestore']();
}

export function LoadColorsFile() {
  return window['go']['main']['App']['LoadColorsFile']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenImgFileDialog() {
  return window['go']['main']['App']['OpenImgFileDialog']();
}

export function OverwriteColorsFiles(arg1, arg2) {
  return window['go']['main']['App']['OverwriteColorsFiles'](arg1, arg2);
}

export function SaveColors(arg1, arg2) {
  return window['go']['main']['App']['SaveColors'](arg1, arg2);
}

export function SaveColorsDialog(arg1) {
  return window['go']['main']['App']['SaveColorsDialog'](arg1);
}

export function StashSelectedImg(arg1, arg2) {
  return window['go']['main']['App']['StashSelectedImg'](arg1, arg2);
}
