// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ColorsBackupRestore():Promise<Array<main.ColorGroup>>;

export function LoadColorsFile():Promise<Array<main.ColorGroup>>;

export function OpenFileDialog():Promise<string>;

export function SaveColors(arg1:Array<main.ColorGroup>):Promise<void>;
