// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ColorsBackupRestore():Promise<Array<main.ColorGroup>>;

export function LoadColorsFile():Promise<main.ColorsFileLoadResult>;

export function OpenFileDialog():Promise<string>;

export function OpenImgFileDialog():Promise<string>;

export function OverwriteColorsFiles(arg1:string,arg2:Array<main.ColorGroup>):Promise<void>;

export function SaveColors(arg1:string,arg2:Array<main.ColorGroup>):Promise<void>;

export function SaveColorsDialog(arg1:Array<main.ColorGroup>):Promise<void>;

export function StashSelectedImg(arg1:string,arg2:string,arg3:string):Promise<string>;
