// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ColorsBackupRestore() {
  return window['go']['main']['App']['ColorsBackupRestore']();
}

export function LoadColorsFile() {
  return window['go']['main']['App']['LoadColorsFile']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveColors(arg1) {
  return window['go']['main']['App']['SaveColors'](arg1);
}
